### ISSUE TITLE
Some labels displayed correctly, some incorrectly as object notation

### ISSUE THREAD

**Issue by sennamint** [shopware/swag-docs-plugin-config#4]
This docs plugin might not be the right spot to blame. ;) Yet it is closest to my issue. When trying to create an advanced custom input field in a plugin using Shopware 6.1.1 dev, I was not able to get the label working properly. I was trying to add a "sw-colorpicker"-component in the config.xml. But its label would not display correctly at the plugin configuration. The label is shown as raw object notation. Same issue with this docs plugin. Some labels are displayed correctly, some not.

![Image of incorrect label display in Backend](https://www.versatil-online.de/_temp/swag-docs-plugin-config-labels-raw.png)

It would be great to get this issue solved soon.

**Comment by mitelg** [comment]
hey @sennamint 
do you use the current 1.1.0 version? Because I'm currently working on bugfixes and improvements for the plugin config system and have already updated the plugin here. But the changes in the core have been done, or will be done in the "master" branch. (which will be SW6.2)
so this is the reason why I doesn't work properly with SW 6.1.1

**Comment by sennamint** [comment]
Hey @mitelg, yes, I was using the current 1.1.0 version of the plugin and the current master branch (6.2.x@dev). Good to hear that the bugfixes are work in progress. In the meantime I'll be waiting for it to become fixed. It's not that urgent for me right now. Thank you for your quick response.

**Comment by mitelg** [comment]
hey @sennamint 
in the meantime, my changes were merged to the master branch https://github.com/shopware/platform/commit/8a2a1931509eb2c41b3340780394fa6b6a50d363
so now the plugin should work in its current state
